resolver: nightly-2018-07-06

packages:
- '.'

extra-deps:
  - linear-1.20.7
  - repa-3.4.1.3
  - git: git@github.com:LumiGuide/haskell-opencv
    commit: b7c1c002e12f29db805c3979d4276dfaf0ab2c3c
    subdirs:
      - opencv
      - opencv-extra

#docker:
#  image: stack-build:lts-10.1-opencv
#  stack-exe: image
